name: Publish NATS Image

on:
  push:
    branches: [main]
    paths:
      - nats/**
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./.github/actions/publish-docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: nats
          tags: ghcr.io/epik-agent/console/nats:latest
